// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZrNasqkHVWMVnxlsOY7vivVxk8MymCc',
    appId: '1:118471401779:web:04d914e800e57215a91e46',
    messagingSenderId: '118471401779',
    projectId: 'gauth-96579',
    authDomain: 'gauth-96579.firebaseapp.com',
    storageBucket: 'gauth-96579.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjl54tRlFOsOUPCQv4a03zL9U4RnkKcKA',
    appId: '1:118471401779:android:c8aa5495da25d53ea91e46',
    messagingSenderId: '118471401779',
    projectId: 'gauth-96579',
    storageBucket: 'gauth-96579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJjo8ZGc6gAyeMLCBVuUEUt25hQVUxcw',
    appId: '1:118471401779:ios:49adabb96b692055a91e46',
    messagingSenderId: '118471401779',
    projectId: 'gauth-96579',
    storageBucket: 'gauth-96579.appspot.com',
    androidClientId: '118471401779-qg5apqpb71l42c57hj9dtep87u7frl52.apps.googleusercontent.com',
    iosClientId: '118471401779-bmdoj3nnd488hut42ab1plk9hs9m9027.apps.googleusercontent.com',
    iosBundleId: 'com.gauth.niranjanauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJjo8ZGc6gAyeMLCBVuUEUt25hQVUxcw',
    appId: '1:118471401779:ios:49adabb96b692055a91e46',
    messagingSenderId: '118471401779',
    projectId: 'gauth-96579',
    storageBucket: 'gauth-96579.appspot.com',
    androidClientId: '118471401779-qg5apqpb71l42c57hj9dtep87u7frl52.apps.googleusercontent.com',
    iosClientId: '118471401779-bmdoj3nnd488hut42ab1plk9hs9m9027.apps.googleusercontent.com',
    iosBundleId: 'com.gauth.niranjanauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZrNasqkHVWMVnxlsOY7vivVxk8MymCc',
    appId: '1:118471401779:web:f2ad639be56c44bfa91e46',
    messagingSenderId: '118471401779',
    projectId: 'gauth-96579',
    authDomain: 'gauth-96579.firebaseapp.com',
    storageBucket: 'gauth-96579.appspot.com',
  );
}
